### ISSUE TITLE
The complete source

### ISSUE THREAD

**Issue by hoangduchuu** [hitherejoe/GithubTrending#9]
hi @hitherejoe , Thanks for your course!
So, is this completed source?
Cloned this repository and can't see the response data in UI of the app. (Only show loading forever)
Please help me how to run the right way to show the UI as your tutorial.

Thanks in advance!

**Comment by ajsf** [comment]
I've been having the same problem, and I was able to solve it by using this version of the project:
https://github.com/graffiti75/GithubTrending

The are a number of differences in that version, such as the GithubTrendingService returning a Flowable vs returning an Observable. The changes that made the difference for me were in the ConfigDao and the isProjectsCacheExpired function in the ProjectsCacheImpl class. It appears that when getConfig is called for the first time, there is an error since no config is saved. This error causes the function to stop, which prevents the getProjects function in the ProjectsDataRepository class from getting the ProjectsRemoteDataStore and calling getProjects.

The getConfig function in the ConfigDao should be changed to return a Maybe:
```
@Query(ConfigConstants.QUERY_CONFIG)
abstract fun getConfig(): Maybe<Config>
```
The isProjectsCacheExpired function in the ProjectsCacheImpl class should be changed to return a Single. The Maybe that is returned from the ConfigDao needs to be converted to a single using the toSingle operator. Here is how the function looks for me after the changes:

```
override fun isProjectsCacheExpired(): Single<Boolean> {
        val currentTime = System.currentTimeMillis()
        val expirationTime = (60 * 10 * 1000).toLong()
        return projectsDatabase
            .configDao()
            .getConfig()
            .onErrorReturn { Config(lastCacheTime = 0) }
            .toSingle()
            .map { currentTime - it.lastCacheTime > expirationTime }
    }
```

Once I made those changes, the project worked for me. I hope this helps. Please let me know if you have any questions.

**Comment by hoangduchuu** [comment]
@ajsf Thanks for your support,
So I have a question for you and @hitherejoe ,
When deleting data from ROOM, How Can I see the data change from UI layer(how can I observe data changes ).
Thanks!
